parameters:
    app.dir.agent.profile: '/agents/images/profile'
    app.dir.event.profile: '/events/images/profile'
    app.dir.initiative.cover: '/initiatives/images/cover'
    app.dir.initiative.profile: '/initiatives/images/profile'
    app.dir.opportunity.cover: '/opportunities/images/cover'
    app.dir.opportunity.profile: '/opportunities/images/profile'
    app.dir.organization.profile: '/organizations/images/profile'
    app.dir.space.profile: '/spaces/images/profile'
    app.dir.space.cover: '/spaces/images/cover'
    app.dir.space.portfolio: '/spaces/images/portfolio'
    app.dir.user.profile: '/users/images/profile'
    app.dir.user.cover: '/users/images/cover'
