list:
  path: /
  controller: App\Controller\Web\Admin\AgentAdminController::list
  methods: ['GET']

create:
  path: /adicionar
  controller: App\Controller\Web\Admin\AgentAdminController::create
  methods: ['GET', 'POST']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\AgentAdminController::remove
  methods: ['GET']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\AgentAdminController::timeline
  methods: ['GET']

edit:
  path: /{id}/editar
  controller: App\Controller\Web\Admin\AgentAdminController::edit
  methods: ['GET', 'POST']

remove_portfolio_photo:
  path: /{id}/portfolio/{photoId}/remove
  controller: App\Controller\Web\Admin\AgentAdminController::removePortfolioPhoto
  methods: ['GET']
