list:
  path: /
  controller: App\Controller\Web\Admin\SpaceAdminController::list
  methods: ['GET']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\SpaceAdminController::remove
  methods: ['GET']

create:
  path: /adicionar
  controller: App\Controller\Web\Admin\SpaceAdminController::create
  methods: ['GET', 'POST']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\SpaceAdminController::timeline
  methods: ['GET']

edit:
  path: /{id}/editar
  controller: App\Controller\Web\Admin\SpaceAdminController::edit
  methods: ['GET', 'POST']

toggle_publish:
  path: /{id}/toggle-publish
  controller: App\Controller\Web\Admin\SpaceAdminController::togglePublish
  methods: ['GET']

remove_portfolio_photo:
  path: /{id}/portfolio/{photoId}/remove
  controller: App\Controller\Web\Admin\SpaceAdminController::removePortfolioPhoto
  methods: ['GET']
